### ISSUE TITLE
Add weighted selection 

### ISSUE THREAD

**Issue by gatear** [datafaker-net/datafaker#1314]
Support weighted faking in custom providers.

Inspired from https://fakerjs.dev/api/helpers#weightedarrayelement
```javascript
faker.helpers.weightedArrayElement([
{ weight: 5, value: 'sunny' }, 
{ weight: 4, value: 'rainy' },
{ weight: 1, value: 'snowy' }
]) // 'sunny', 50% of the time, 'rainy' 40% of the time, 'snowy' 10% of the time
```

With custom providers, we could make a YML provider with weights associated to each value
```yml
en:
  faker:
    insectsfromfile:
      ants: [5, 'Driver ant', 4, 'Fire ant', 1, 'Harvester ant']

```
Questions
- Is there a way to achieve weighted faking with current codebase ?

**Comment by bodiam** [comment]
Hi @gatear , I think there is a way, but it's a very poor way: I think by repeating the element a few times, you could achieve the same, though perhaps the fakerjs way is a bit more elegant?

**Comment by gatear** [comment]
Agreed, it's a good workaround. Actually used something like this today.
```yaml
en:
  faker:
    insectsfromfile:
      ants: ['Driver ant', 'Harvester ant', 'Harvester ant', 'Harvester ant'] 
```
So in theory we would have 75% chances of getting 'Harvester ant'.
That being said I think it's valuable to offer an explicit way of configuring this.
