### ISSUE TITLE
ru-MD cities names

### ISSUE THREAD

**Issue by ksy-ke** [datafaker-net/datafaker#1358]
Hello! 
I found that the city names in the ru-MD.yml file are not in Russian. Is it supposed to be like that, or should they be translated?

**Comment by asolntsev** [comment]
@ksy-ke Good point: city names in `ru-MD.yml` should be Moldovan cities, but translated to Russian. 

Like
```yml
ru-MD:
  faker:
    address:
      city_name: [ "Кишинёв", "Бельцы", "Бендеры", ...]
```
