### ISSUE TITLE
Mark tags as GitHub releases

### ISSUE THREAD

**Issue by axelfontaine** [datafaker-net/datafaker#1401]
This makes it possible to get GitHub notifications when watching the repo for releases only.

Release notes can then also be attached to those releases to make everything directly visible from GitHub.

**Comment by bodiam** [comment]
I am not really sure what you mean here. What does "mark tags as github releases" mean?

**Comment by kingthorin** [comment]
I believe they mean here: https://github.com/datafaker-net/datafaker/releases

As you can see there are 41 tags but zero releases.

I'll look at adding a workflow that we create GitHub releases based on tags being applied. (Unless someone is against the idea for some reason.)

**Comment by bodiam** [comment]
Thanks @kingthorin . I have no objection to this at all, it's just not something I use myself, plus I'm not sure how to actually create a GitHub release using Maven. 

Maybe we should tackle a long outstanding issue here to make creating releases a bit easier by having a GitHub workflow?

**Comment by asolntsev** [comment]
In my own project, I always create releases. It helps people understand what's coming in a next release.
Also, dependabot attaches the release description to its pull requests. 

For example: https://github.com/selenide/selenide/releases

I do the release manually when I upload a new jar to Maven central. 
But there is a script that automatically prepares a draft release description: https://github.com/selenide/selenide/blob/main/.github/release-drafter.yml

**Comment by bodiam** [comment]
@asolntsev Thanks. I don't mind clicking a few buttons here and there, but it would be nice if we could release the whole project just by triggering a GitHub action or so.

**Comment by kingthorin** [comment]
Can you describe the current manual process or is it documented somewhere? 

I'm sure it's mostly automateable. A few other Java projects I work on release to maven, though they use grade for building.

**Comment by bodiam** [comment]
Currently, I do something like:

`mvn release:prepare release:perform`

But it needs a GPG key (I think I've added it in the secrets here), plus it needs to have the next version as an input (if our current version is 2.4.1 snapshot, then sometimes we create 2.4.1, sometimes 2.5.0, depending on the features) and perhaps the tag name, though that should be equal to the version number.

I think that's about it.

**Comment by kingthorin** [comment]
If you can let me know the name of the repo secret for the pgp key, I'll get a PR together.

**Comment by kingthorin** [comment]
Oh I see you started a workflow about 4 months ago. The run logs are no longer available, mind if I re-run it to see why/how it is failing?

**Comment by bodiam** [comment]
@kingthorin absolutely, feel free to try it!

**Comment by bodiam** [comment]
The secret names are:

OSSRH_TOKEN
OSSRH_USERNAME
GPG_SIGNING_KEY

**Comment by kingthorin** [comment]
Okay so the release workflow is failing on gpg pieces. I see in the deploy workflow you base64 decode the gpg key before it's used. Can you create a secret that holds the decoded form to start with and we can try that, perhaps use it in both workflows ultimately.

**Comment by bodiam** [comment]
@kingthorin I've updated the GPG_SIGNING_KEY, it's now set to to:

```
-----BEGIN PGP PRIVATE KEY BLOCK-----

lFgEY..... <stuff>

-----END PGP PRIVATE KEY BLOCK-----
```

**Comment by bodiam** [comment]
It seems we don't need that Github actio, something like this could be enough:

```
name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
```

See https://medium.com/@jtbsorensen/publish-your-artifact-to-the-maven-central-repository-using-github-actions-15d3b5d9ce88
