### ISSUE TITLE
Expression List

### ISSUE THREAD

**Issue by esaretabut** [datafaker-net/datafaker#1498]
Greetings,

I couldn't find it in your documents.

Is there a way we can get a list of expressions? For example:

Classes that extend the `AbstractProvider<BaseProviders>` class:

```java
resolve("address.street_name")
resolve("barcode.types")
resolve("music.instruments")
```
i.e.

If we can get this list, we can know what to write in the expression and for example, we can provide completion to the user in the front-end.

Best

**Comment by snuyanzin** [comment]
For 90-95% of cases you can read it from yaml file in resources.
There are 5-10% notoriously tricky when either the next part is also generated or is handled in some other way (not yaml)

**Comment by asolntsev** [comment]
@esaretabut You don't really need to use those expressions. DataFaker library provides Java API to generate streets, musical instruments etc.:

```java
faker.address().streetName();
faker.barcode().type();
faker.music().instrument();
```

**Comment by esaretabut** [comment]
Actually I was working on yaml files. For example I want to parse and get keys `color.name` from the `color.yml` file below and parse/get keys from all other yaml files (i.e `x.y.z`) to create an expression list.

```yml
en:
  faker:
    color:
      name:
      - "red"
      - "green"
      - "blue"
      - "yellow"
      - "purple"
      - "mint green"
      - "teal"
      - "white"
      - "black"
      - "orange"
      - "pink"
      - "grey"
      - "maroon"
      - "violet"
      - "turquoise"
      - "tan"
      - "sky blue"
      - "salmon"
      - "plum"
      - "orchid"
      - "olive"
      - "magenta"
      - "lime"
      - "ivory"
      - "indigo"
      - "gold"
      - "fuchsia"
      - "cyan"
      - "azure"
      - "lavender"
      - "silver"
```

Thanks for your advice @snuyanzin
