### ISSUE TITLE
Inconsistent province-city combinations when using new Faker(Locale.CHINA)

### ISSUE THREAD

**Issue by xzxiaoshan** [datafaker-net/datafaker#1551]
When using `new Faker(Locale.CHINA)` and calling methods on the `address()` object, the generated province and city do not maintain real-world geographic relationships.

For example, it may generate an address like "福建省南京市" ("Fujian Province, Nanjing City"), but Nanjing is actually a city in Jiangsu Province, not Fujian.

This lack of correlation may cause issues when generating realistic Chinese address data, especially for applications requiring location accuracy (e.g., testing address validation or shipping systems).

Suggestion:
- Consider introducing a mapping structure to ensure generated provinces and cities are geographically accurate.
- Alternatively, provide an option to toggle “realistic mode” vs. “random mode” for Chinese address generation.

Thanks for your great work on this library!

```java

    /**
     * 生成随机地址（包含省、市、街道）
     *
     * @return 随机地址
     */
    public static String generateAddress() {
        Address address = FAKER_ZH.address();
        String city = address.city();
        if (!city.endsWith("市")) {
            city = city.concat("市");
        }
        return address.state().concat(city).concat(address.streetAddress());
    }

```

**Comment by asolntsev** [comment]
@xzxiaoshan The idea is valid. I just think that DataFaker was not meant to be so precise. 

But how to achieve that?

Then we should change the existing mappings. Instead of 2 lists `province` and `city_name`:
```yml
      province: [Aceh, Bali, DI Yogyakarta, DKI Jakarta]
      city_name: [Aceh Barat, Aceh Barat Daya, Bengkulu Utara, Berau, Biak Numfor, Bima, Binjai, Jakarta Utara, Jambi]
```

We should introduce a structure like this:

```yml
      provinces:
        - name: Aceh
          cities: [Aceh Barat, Aceh Barat Daya]
        - name: Bali
          cities: [Bengkulu Utara, Berau]
        - name: DI Yogyakarta
          cities: [Biak Numfor, Bima, Binjai, Jakarta Utara]
        - name: DKI Jakarta
          cities: [Jambi]
```

Apparently, this is a big job. How is going to do that?

(but we can migrate countries one-by-one, supporting both old and new format)
