### ISSUE TITLE
A bug in the job method

### ISSUE THREAD

**Issue by Gandhi-gd** [datafaker-net/datafaker#370]
**Describe the bug**
The bug about Chinese still exists, just like the  https://github.com/DiUS/java-faker/ library
**To Reproduce**
```java
import net.datafaker.Faker;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Locale;

@SpringBootTest
class SpringBootStudyApplicationTests {

    @Test
    void testFaker() {
        Faker faker = new Faker(Locale.CHINA);
        System.out.println(faker.name().name());
        System.out.println(faker.job().field());
        System.out.println(faker.job().position());
        System.out.println(faker.job().title());
    }
}
```
result
![image](https://user-images.githubusercontent.com/55038394/190939627-38d39d74-3d56-4d1f-a39c-8e8bad881945.png)

**Versions:**
 - OS: windows
 - JDK 8
 - Faker 1.6.0

**Comment by bodiam** [comment]
Sorry, but what is the bug exactly? What did  expect to see instead?

**Comment by Gandhi-gd** [comment]
> Sorry, but what is the bug exactly? What did expect to see instead?

I have set Chinese, so it should be that all the output is Chinese like the name method

**Comment by bodiam** [comment]
There is unfortunately no translated job information in the `zh-CN.yml` file. The only translations we have is in `hy.yml`, pt-BR.yml`, and the default English. 

We'd absolutely love contributions in this. My understanding of the Chinese language is poor, but If you'd be willing to help translate this data, or a subset of it, we'd be very happy to include it in the library.

These are the fields which need translating:

```
    job:
      field: [Marketing, IT, Accounting, Administration, Advertising, Banking, Community-Services, Construction, Consulting, Design, Education, Farming, Government, Healthcare, Hospitality, Legal, Manufacturing, Marketing, Mining, Real-Estate, Retail, Sales, Technology]
      seniority: [Lead, Senior, Product, National, Regional, District, Central, Global, Customer, Investor, Dynamic, International, Legacy, Forward, Internal, Chief, Direct, Corporate, Future, Human, Principal]
      position: [Supervisor, Associate, Executive, Liaison, Officer, Manager, Engineer, Specialist, Director, Coordinator, Administrator, Architect, Analyst, Designer, Planner, Orchestrator, Technician, Developer, Producer, Consultant, Assistant, Facilitator, Agent, Representative, Strategist]
      key_skills: [Teamwork, Communication, Problem solving, Leadership, Organisation, Work under pressure, Confidence, Self-motivated, Networking skills, Proactive, Fast learner, Technical savvy]
      employment_type: [Full-time, Part-time, Temporary, Contract, Internship, Commission]
      education_level: [Associates, Bachelor, Master, Doctorate]
```
