### ISSUE TITLE
Expand NO local names

### ISSUE THREAD

**Issue by robosoul** [datafaker-net/datafaker#636]
**Is your feature request related to a problem? Please describe.**
There are no first/last name collections for locale `no`.

**Describe the solution you'd like**
Create `name` section (for `no` locale) with following collections:
```
no:
  faker:
    name:
      female_first_name: []
      male_first_name: []
      last_name: []
      prefix: []
      name_with_middle:
        - "#{prefix} #{first_name} #{last_name} #{last_name}"
        - "#{first_name} #{last_name} #{last_name}"
        - "#{first_name} #{last_name} #{last_name}"
        - "#{first_name} #{last_name} #{last_name}"
        - "#{first_name} #{last_name} #{last_name}"
      first_name:
        - "#{female_first_name}"
        - "#{male_first_name}"

      title:
        descriptor: []
        level: []
        job: []
      name:
        - "#{first_name} #{last_name}"
        - "#{prefix} #{first_name} #{last_name}"
```

**Describe alternatives you've considered**
Created local file that I plan to move to this repo.
