### ISSUE TITLE
Reusable merge of male/female names into first_names list

### ISSUE THREAD

**Issue by robosoul** [datafaker-net/datafaker#644]
**Is your feature request related to a problem? Please describe.**
For following locales:
- src/main/resources/en-PH.yml
- src/main/resources/fi-FI.yml
- src/main/resources/nb-NO.yml

Male and female first names are simply copy/pasted to `first_name` list. Example from `en-PH`:
```yaml
      male_first_name: [Michael, Christian, Jeffrey, Jayson, Richard, Ryan, Jonathan, Joseph, Alvin, Marvin, Joel, Christopher, Julius, Angelo, Emmanuel]
      female_first_name: [Michelle, Jennifer, Catherine, Mary Grace, Angelica, Maricel, Rowena, Joan, Jocelyn, Mary Ann, Jessica, Arlene, Melanie, Mary Jane, Janice, Rosemarie, Christine, Marjorie, Analyn, Josephine]
      first_name: [Michael, Christian, Jeffrey, Jayson, Richard, Ryan, Jonathan, Joseph, Alvin, Marvin, Joel, Christopher, Julius, Angelo, Emmanuel, Michelle, Jennifer, Catherine, Mary Grace, Angelica, Maricel, Rowena, Joan, Jocelyn, Mary Ann, Jessica, Arlene, Melanie, Mary Jane, Janice, Rosemarie, Christine, Marjorie, Analyn, Josephine]     
```

**Describe the solution you'd like**
We should use most common (reusable) approach, where `first_name` is combo (not copy/pasted) of `male_first_name` and `female_first_name` values:
```yaml
      first_name:
        - "#{male_first_name}"
        - "#{female_first_name}"
```

**Describe alternatives you've considered**
/

**Additional context**
/
